[project]
name = "oae-firmware"
version = "0.1.0"
description = "Firmware and associated software for Global Health's low-cost OAE screening device"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pyserial (>=3.5,<4.0)", "numpy (>=2.2.5,<3.0.0)"]

[tool.setuptools]
packages = ["tools"]

[project.scripts]
oae_serial_host = "tools.oae_serial.oae_serial_host:main"

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]
ignore = [
  "E501", # ignore line length
]
