#include "main.h"
#include "arm_math.h"
#define NS  128
#define n_data 1000
#define M_PI 3.14159265358979323846

int16_t Wave_Data[n_data * 2];    // n_data is defined as 1000
uint8_t Wave_buf_empty = 1;
 
//Extern any autogenerated referenced variables
extern DAC_HandleTypeDef hdac1;
extern DMA_HandleTypeDef hdma_dac_ch1;
extern TIM_HandleTypeDef htim2;

//extern SAI_HandleTypeDef hsai_BlockA1;
//extern DMA_HandleTypeDef hdma_sai1_a;

//Runs once after all peripherals are initialized
void app_setup(){
    uint32_t Wave_LUT[NS] = {
            2048, 2149, 2250, 2350, 2450, 2549, 2646, 2742, 2837, 2929, 3020, 3108, 3193, 3275, 3355,
            3431, 3504, 3574, 3639, 3701, 3759, 3812, 3861, 3906, 3946, 3982, 4013, 4039, 4060, 4076,
            4087, 4094, 4095, 4091, 4082, 4069, 4050, 4026, 3998, 3965, 3927, 3884, 3837, 3786, 3730,
            3671, 3607, 3539, 3468, 3394, 3316, 3235, 3151, 3064, 2975, 2883, 2790, 2695, 2598, 2500,
            2400, 2300, 2199, 2098, 1997, 1896, 1795, 1695, 1595, 1497, 1400, 1305, 1212, 1120, 1031,
            944, 860, 779, 701, 627, 556, 488, 424, 365, 309, 258, 211, 168, 130, 97,
            69, 45, 26, 13, 4, 0, 1, 8, 19, 35, 56, 82, 113, 149, 189,
            234, 283, 336, 394, 456, 521, 591, 664, 740, 820, 902, 987, 1075, 1166, 1258,
            1353, 1449, 1546, 1645, 1745, 1845, 1946, 2047
    };
    HAL_DAC_Start_DMA(&hdac1, DAC_CHANNEL_1, (uint32_t*)Wave_LUT, 128, DAC_ALIGN_12B_R);
    HAL_TIM_Base_Start(&htim2);
//    float32_t FFT_Input_Q15_f[50];
//    float32_t aFFT_Input_Q15[50];
//    #define FFT_Length  1024
//    arm_float_to_q15((float32_t *)&FFT_Input_Q15_f[0], (q15_t *)&aFFT_Input_Q15[0], FFT_Length*2);
//    arm_hamming_f32((float32_t *)&FFT_Input_Q15_f[0], FFT_Length);
//
//    for (int i = 0; i < n_data; i++) {
//        Wave_Data[i * 2] = (int16_t) (sin(2. * M_PI * 8. * i / 1000.) * 500);
//        Wave_Data[i * 2 + 1] = (int16_t) (sin(2. * M_PI * 10. * i / 1000.) * 500);
//    };
//	HAL_SAI_Transmit_DMA(&hsai_BlockA1, (uint16_t*) Wave_Data, (uint16_t) n_data * 2);
}

//Runs repeatedly after app_setup() has finished
void app_loop() {
    HAL_GPIO_TogglePin(LD3_GPIO_Port, LD3_Pin);
    HAL_Delay(1000);
    HAL_GPIO_TogglePin(LD3_GPIO_Port, LD3_Pin);
    HAL_Delay(100);
}

