name: Firmware Build For PRs (CliffBar)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - 'OAE_CliffBar/**/*.c'
  workflow_dispatch:

env:
  PROJECT_NAME: 'OAE_CliffBar'

jobs:
  build:
    name: "Building Firmware (Debug)"
    runs-on: ubuntu-latest
    container:
      image: xanderhendriks/stm32cubeide:16.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        uses: xanderhendriks/action-build-stm32cubeide@v16.0
        with:
          project-path: './${{ env.PROJECT_NAME }}'
          project-target: "${{ env.PROJECT_NAME }}/Debug"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PROJECT_NAME }}.elf"
          path: "${{ env.PROJECT_NAME }}/Debug"