name: Firmware Build For PRs (SwedishFish)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]   
    paths:
      - 'OAE_SwedishFish/**.c'

jobs:
  build:
    runs-on: ubuntu-latest